import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  ImageRun,
  ExternalHyperlink,
  InternalHyperlink,
} from 'docx';
import { ReportData, BrandContext } from '@/lib/report-analysis';
import { saveAs } from 'file-saver';

// Helper function to load image as Uint8Array for docx (more reliable than ArrayBuffer)
async function loadImageAsUint8Array(url: string): Promise<Uint8Array> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to load image: ${response.statusText}`);
    }
    const arrayBuffer = await response.arrayBuffer();
    return new Uint8Array(arrayBuffer);
  } catch (error) {
    console.error('Error loading image:', error);
    throw error;
  }
}

export async function generateWordDocument(
  reportData: ReportData,
  clientName?: string,
  brandContext?: BrandContext
): Promise<void> {
  const sections = [];
  
  // Load logo image
  let logoImage: ImageRun | null = null;
  try {
    const logoData = await loadImageAsUint8Array('/logo_Nytro_color.png');
    // Logo is 1126x1124 (nearly square, 1:1 aspect ratio)
    // Using 200px for both width and height to maintain square aspect ratio
    logoImage = new ImageRun({
      data: logoData,
      type: 'png', // Explicitly specify PNG type to prevent unreadable content errors
      transformation: {
        width: 200, // pixels - docx will convert to EMU internally
        height: 200, // pixels - maintain square aspect ratio (logo is 1126x1124)
      },
    });
  } catch (error) {
    console.warn('Could not load logo, using text fallback:', error);
  }

  // Cover Page
  sections.push({
    properties: {},
    children: [
      ...(logoImage ? [
        new Paragraph({
          children: [logoImage],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
      ] : [
        new Paragraph({
          children: [
            new TextRun({
              text: 'Nytro.ai',
              bold: true,
              size: 32,
              color: 'F96E11',
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
      ]),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Asset Strategy Audit',
            bold: true,
            size: 48,
            color: 'F96E11',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `${clientName || 'Client'} Content Library Analysis`,
            size: 28,
            color: '6b7280',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated: ${new Date(reportData.generatedAt).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}`,
            size: 24,
            color: '374151',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 600 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by Nytro.ai • Professional Content Strategy Analysis',
            size: 20,
            color: '6b7280',
            italics: true,
          }),
        ],
        alignment: AlignmentType.CENTER,
      }),
    ],
  });

  // Executive Summary
  sections.push({
    properties: {},
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Executive Summary',
            bold: true,
            size: 36,
            color: 'F96E11',
          }),
        ],
        spacing: { after: 300 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `${reportData.healthScore}%`,
            bold: true,
            size: 72,
            color: '059669',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Content Health Score',
            size: 32,
            color: '6b7280',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      }),
      // Metrics Table
      new Table({
        width: {
          size: 100,
          type: WidthType.PERCENTAGE,
        },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: `${reportData.inventoryBreakdown.total}`,
                        bold: true,
                        size: 36,
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Total Assets',
                        size: 20,
                        color: '6b7280',
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                width: { size: 33.33, type: WidthType.PERCENTAGE },
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: `${reportData.coverageHeatmap.totalPersonas}`,
                        bold: true,
                        size: 36,
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Target Personas',
                        size: 20,
                        color: '6b7280',
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                width: { size: 33.33, type: WidthType.PERCENTAGE },
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: `${reportData.coverageHeatmap.totalGaps}`,
                        bold: true,
                        size: 36,
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Coverage Gaps',
                        size: 20,
                        color: '6b7280',
                      }),
                    ],
                    alignment: AlignmentType.CENTER,
                  }),
                ],
                width: { size: 33.33, type: WidthType.PERCENTAGE },
              }),
            ],
          }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Top Strategic Wins',
            bold: true,
            size: 28,
            color: 'F96E11',
          }),
        ],
        spacing: { before: 400, after: 200 },
      }),
      ...reportData.strategicWins.slice(0, 3).map(
        (win) =>
          new Paragraph({
            children: [
              new TextRun({
                text: '✓ ',
                color: '059669',
                bold: true,
              }),
              new TextRun({
                text: win,
                size: 22,
              }),
            ],
            spacing: { after: 150 },
          })
      ),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Critical Gaps Requiring Attention',
            bold: true,
            size: 28,
            color: 'F96E11',
          }),
        ],
        spacing: { before: 400, after: 200 },
      }),
      ...[
        ...reportData.gapAnalysis.criticalGaps.slice(0, 2),
        ...reportData.gapAnalysis.contentGaps.slice(0, 1),
      ].flatMap((gap) => [
        new Paragraph({
          children: [
            new TextRun({
              text: gap.title,
              bold: true,
              size: 24,
            }),
          ],
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: gap.description,
              size: 22,
              color: '6b7280',
            }),
          ],
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `${gap.severity.toUpperCase()} PRIORITY`,
              size: 18,
              color: 'dc2626',
              bold: true,
            }),
          ],
          spacing: { after: 200 },
        }),
      ]),
    ],
  });

  // Brand Identity Page
  if (brandContext) {
    sections.push({
      properties: {},
      children: [
        new Paragraph({
          children: [
            new TextRun({
              text: 'Company Overview',
              bold: true,
              size: 36,
              color: 'F96E11',
            }),
          ],
          spacing: { after: 300 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: `Understanding ${clientName || 'the organization'} before analyzing content strategy`,
              size: 24,
              color: '374151',
              italics: true,
            }),
          ],
          spacing: { after: 400 },
        }),
        ...(brandContext.valueProposition
          ? [
              new Paragraph({
                text: 'Value Proposition',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: brandContext.valueProposition,
                    size: 22,
                  }),
                ],
                spacing: { after: 400 },
              }),
            ]
          : []),
        ...(brandContext.painClusters && brandContext.painClusters.length > 0
          ? [
              new Paragraph({
                text: 'Problems We Solve',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              ...brandContext.painClusters.map(
                (pain) =>
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: '• ',
                        size: 22,
                      }),
                      new TextRun({
                        text: pain,
                        size: 22,
                      }),
                    ],
                    spacing: { after: 150 },
                  })
              ),
            ]
          : []),
        ...(brandContext.primaryICPRoles && brandContext.primaryICPRoles.length > 0
          ? [
              new Paragraph({
                text: 'Key Decision Makers',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: 'Primary buyer personas and job titles:',
                    size: 22,
                    color: '374151',
                  }),
                ],
                spacing: { after: 200 },
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: brandContext.primaryICPRoles.join(', '),
                    size: 22,
                  }),
                ],
                spacing: { after: 400 },
              }),
            ]
          : []),
        ...(brandContext.targetIndustries && brandContext.targetIndustries.length > 0
          ? [
              new Paragraph({
                text: 'Target Industries',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              new Paragraph({
                children: [
                  new TextRun({
                    text: brandContext.targetIndustries.join(', '),
                    size: 22,
                  }),
                ],
                spacing: { after: 400 },
              }),
            ]
          : []),
        ...(brandContext.useCases && brandContext.useCases.length > 0
          ? [
              new Paragraph({
                text: 'How Customers Use Our Solutions',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              ...brandContext.useCases.slice(0, 3).map(
                (useCase) =>
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: '• ',
                        size: 22,
                      }),
                      new TextRun({
                        text: useCase,
                        size: 22,
                      }),
                    ],
                    spacing: { after: 150 },
                  })
              ),
            ]
          : []),
        ...(brandContext.keyDifferentiators && brandContext.keyDifferentiators.length > 0
          ? [
              new Paragraph({
                text: 'What Makes Us Different',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 200 },
              }),
              ...brandContext.keyDifferentiators.map(
                (differentiator) =>
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: '✓ ',
                        color: '059669',
                        bold: true,
                      }),
                      new TextRun({
                        text: differentiator,
                        size: 22,
                      }),
                    ],
                    spacing: { after: 150 },
                  })
              ),
            ]
          : []),
      ],
    });
  }

  // Funnel Health Page
  sections.push({
    properties: {},
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Deep Dive - Funnel Health',
            bold: true,
            size: 36,
            color: 'F96E11',
          }),
        ],
        spacing: { after: 300 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Distribution of content assets across the customer journey stages',
            size: 24,
            color: '374151',
            italics: true,
          }),
        ],
        spacing: { after: 400 },
      }),
      // Funnel Stage Table
      new Table({
        width: {
          size: 100,
          type: WidthType.PERCENTAGE,
        },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Funnel Stage',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Assets',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Percentage',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Status',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
          ...Object.entries(reportData.inventoryBreakdown.byStage).map(([stage, count]) => {
            const countNum = count as number;
            const percentage =
              reportData.inventoryBreakdown.total > 0
                ? Math.round((countNum / reportData.inventoryBreakdown.total) * 100)
                : 0;
            const status = stage === 'BOFU_DECISION' && percentage < 10 ? '⚠️ Low' : '✓ Good';

            return new TableRow({
              children: [
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: stage.replace('_', ' '),
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: count.toString(),
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: `${percentage}%`,
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: status,
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            });
          }),
        ],
      }),
      new Paragraph({
        text: 'Asset Type Distribution',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
      new Table({
        width: {
          size: 100,
          type: WidthType.PERCENTAGE,
        },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Asset Type',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Count',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
          ...Object.entries(reportData.inventoryBreakdown.byAssetType).map(([type, count]) =>
            new TableRow({
              children: [
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: type,
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: count.toString(),
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            })
          ),
        ],
      }),
    ],
  });

  // Persona Coverage Page
  sections.push({
    properties: {},
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Deep Dive - Persona Coverage',
            bold: true,
            size: 36,
            color: 'F96E11',
          }),
        ],
        spacing: { after: 300 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Content coverage heatmap showing which personas have assets at each funnel stage',
            size: 24,
            color: '374151',
            italics: true,
          }),
        ],
        spacing: { after: 400 },
      }),
      new Table({
        width: {
          size: 100,
          type: WidthType.PERCENTAGE,
        },
        rows: [
          new TableRow({
            children: [
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Persona',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'TOFU',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'MOFU',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'BOFU',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Retention',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: 'Coverage',
                        bold: true,
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
          ...Object.entries(reportData.coverageHeatmap.personaCoverage).map(([persona, stages]) => {
            const stageCounts = stages as Record<string, number>;
            const coveredStages = Object.values(stageCounts).filter(count => count > 0).length;
            const totalStages = Object.keys(stageCounts).length;
            const coveragePercent = Math.round((coveredStages / totalStages) * 100);

            return new TableRow({
              children: [
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: persona,
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: stageCounts.TOFU_AWARENESS > 0 ? stageCounts.TOFU_AWARENESS.toString() : '—',
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: stageCounts.MOFU_CONSIDERATION > 0 ? stageCounts.MOFU_CONSIDERATION.toString() : '—',
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: stageCounts.BOFU_DECISION > 0 ? stageCounts.BOFU_DECISION.toString() : '—',
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: stageCounts.RETENTION > 0 ? stageCounts.RETENTION.toString() : '—',
                        }),
                      ],
                    }),
                  ],
                }),
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [
                        new TextRun({
                          text: `${coveragePercent}%`,
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            });
          }),
        ],
      }),
      new Paragraph({
        text: 'Neglected Personas',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
      ...Object.entries(reportData.coverageHeatmap.personaCoverage)
        .filter(([, stages]) => Object.values(stages as Record<string, number>).every((count) => count === 0))
        .flatMap(([persona]) => [
          new Paragraph({
            children: [
              new TextRun({
                text: persona,
                bold: true,
                size: 24,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'No content assets found for this persona',
                size: 22,
                color: '6b7280',
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'CRITICAL GAP',
                size: 18,
                color: 'dc2626',
                bold: true,
              }),
            ],
            spacing: { after: 200 },
          }),
        ]),
    ],
  });

  // Action Plan Page
  sections.push({
    properties: {},
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: 'Action Plan',
            bold: true,
            size: 36,
            color: 'F96E11',
          }),
        ],
        spacing: { after: 300 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Prioritized recommendations to improve your content strategy',
            size: 24,
            color: '374151',
            italics: true,
          }),
        ],
        spacing: { after: 400 },
      }),
      new Paragraph({
        text: 'Recommended Assets to Create',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 200 },
      }),
      ...reportData.recommendations.map(
        (recommendation, index) =>
          new Paragraph({
            children: [
              new TextRun({
                text: `${index + 1}. `,
                bold: true,
              }),
              new TextRun({
                text: recommendation,
                size: 22,
              }),
            ],
            spacing: { after: 150 },
          })
      ),
      new Paragraph({
        text: 'Implementation Priority',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: '1. Address critical gaps (missing personas) - High impact, immediate action needed',
            size: 22,
          }),
        ],
        spacing: { after: 150 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: '2. Improve BOFU content coverage - Essential for conversion optimization',
            size: 22,
          }),
        ],
        spacing: { after: 150 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: '3. Address unmentioned pain points - Fill content gaps in existing personas',
            size: 22,
          }),
        ],
        spacing: { after: 150 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: '4. Optimize and refresh existing content - Maintain quality and relevance',
            size: 22,
          }),
        ],
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by Nytro.ai',
            size: 18,
            color: '6b7280',
            italics: true,
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: { before: 400 },
      }),
    ],
  });

  const doc = new Document({
    sections,
  });

  const blob = await Packer.toBlob(doc);
  const timestamp = new Date().toISOString().split('T')[0];
  const clientPrefix = clientName ? `${clientName.replace(/\s+/g, '_')}_` : '';
  saveAs(blob, `${clientPrefix}Asset_Strategy_Report_${timestamp}.docx`);
}
